sudo: required
language: scala
scala:
  - 2.12.12
services:
  - docker
jdk:
  - openjdk8
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.custom-cache
script:
  - sbt -jvm-opts .jvmopts-travis clean coverage fixCheck test coverageReport coverageAggregate
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - >
    test "${TRAVIS_PULL_REQUEST}" = 'false' &&
    test "${TRAVIS_REPO_SLUG}" = 'radicalbit/NSDb' &&
    test "${TRAVIS_JDK_VERSION}" = 'oraclejdk8' &&
    sh "$TRAVIS_BUILD_DIR/travis-credentials.sh" &&
    sbt publish
    sbt docker:publishLocal
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker image ls
  - docker push DOCKER_USERNAME/nsdb:1.0.0-SNAPSHOT
